version: '3.4'

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /home/holomia/manager_device
    volumes:
      - ./:/home/holomia/manager_device
    depends_on:
      - db
      - redis
      - nodejs
      


  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
       - ${APP_PORT}:80
      # - 443:443
    volumes:
      - ./:/home/holomia/manager_device
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/


  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .docker/data/db:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:80
    environment:
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 4096M
    depends_on:
      - db

  nodejs:
    build:
      context: .docker/nodejs
      dockerfile: Dockerfile
    restart: unless-stopped


  redis:
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped

