version: '3.4'

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /home/holomia/manager_device
    volumes:
      - ./:/home/holomia/manager_device
    depends_on:
      - db
      - redis
      # - laravel_echo_server
      


  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
       - ${APP_PORT}:80
      # - 443:443
    volumes:
      - ./:/home/holomia/manager_device
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
        SOKETI_DEBUG: '1'
        SOKETI_METRICS_SERVER_PORT: '9601'
    ports:
        - '${SOKETI_PORT:-6001}:6001'
        - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'


  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .docker/data/db:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:80
    environment:
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 4096M
    depends_on:
      - db

  # laravel_echo_server:
  #   build:
  #     context: .docker/laravel-echo-server
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .env:/app/.env
  #   restart: unless-stopped
  # npm:  
  #   image: node:16-alpine
  #   working_dir: /home/holomia/manager_device
  #   entrypoint: ["node","server"]
  #   ports:
  #     - 3000:80
  #   volumes: 
  #     - ./:/home/holomia/manager_device
 
  redis:
    image: redis:6-alpine
    working_dir: /home/holomia/manager_device
    ports:
      - 6379:6379
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped


